import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CheckCircle2, XCircle, ArrowLeft, Loader2 } from "lucide-react";
import { useOrganization } from "@/contexts/OrganizationContext";

export default function PaymentCallback() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { organization } = useOrganization();
  const [countdown, setCountdown] = useState(3);

  // Determine status from URL query params (standard Stripe behavior)
  // If ?bill_id is present, it's a patient payment (generated by our function)
  // If ?session_id is present, it might be a subscription (from create-checkout)
  // Our backend logic directs success to this page.
  // We can infer success if not canceled, or explicit param.
  const isCanceled = searchParams.get("canceled") === "true";
  const isSuccess = !isCanceled;

  useEffect(() => {
    if (isSuccess) {
      const interval = setInterval(() => {
        setCountdown((prev) => prev - 1);
      }, 1000);

      const timer = setTimeout(() => {
         // Determine redirect destination
         if (organization?.slug) {
             // If we have a bill_id, maybe go to Financeiro?
             // For now, default to dashboard/subscription as requested or generic financial page
             if (searchParams.get("bill_id")) {
                 // It was a patient payment
                 navigate("/financeiro");
             } else {
                 // Likely a subscription payment
                 navigate(`/portal/${organization.slug}/assinatura`);
             }
         } else {
             navigate('/dashboard');
         }
      }, 3000);

      return () => {
        clearTimeout(timer);
        clearInterval(interval);
      };
    }
  }, [isSuccess, navigate, organization, searchParams]);

  if (isCanceled) {
      return (
        <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
          <Card className="w-full max-w-md shadow-xl border-red-100">
            <CardHeader className="flex flex-col items-center gap-4 pb-2">
              <div className="h-16 w-16 bg-red-100 rounded-full flex items-center justify-center">
                <XCircle className="h-10 w-10 text-red-500" />
              </div>
              <CardTitle className="text-2xl font-bold text-red-700">Pagamento Cancelado</CardTitle>
            </CardHeader>
            <CardContent className="text-center space-y-2">
              <p className="text-gray-600">
                O processo de pagamento foi interrompido. Nenhum valor foi cobrado do seu cartão.
              </p>
              <p className="text-sm text-gray-500">
                Você pode tentar novamente a qualquer momento.
              </p>
            </CardContent>
            <CardFooter className="justify-center pt-2">
                <Button variant="default" onClick={() => navigate(-1)} className="w-full">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Voltar
                </Button>
            </CardFooter>
          </Card>
        </div>
      );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <Card className="w-full max-w-md shadow-xl border-green-100">
        <CardHeader className="flex flex-col items-center gap-4 pb-2">
          <div className="h-20 w-20 bg-green-100 rounded-full flex items-center justify-center animate-pulse">
            <CheckCircle2 className="h-12 w-12 text-green-600" />
          </div>
          <CardTitle className="text-2xl font-bold text-green-700">Pagamento Confirmado!</CardTitle>
        </CardHeader>
        <CardContent className="text-center space-y-4">
          <p className="text-gray-600 text-lg">
            Sua transação foi processada com sucesso.
          </p>
          <div className="flex items-center justify-center gap-2 text-sm text-gray-500">
            <Loader2 className="h-4 w-4 animate-spin text-primary" />
            Atualizando sistema e redirecionando em {countdown}s...
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
